# Generated by Django 5.2.14 on 2026-05-09 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('telephone', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('longitude', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload/images/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gauge_checker.location')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_measured', models.DateField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('consumed', models.IntegerField()),
                ('Images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='gauge_checker.images')),
            ],
        ),
        migrations.CreateModel(
            name='Gauge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_calibrated', models.DateField()),
                ('type', models.CharField(max_length=100)),
                ('date_installed', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('serial', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_consumed', models.IntegerField()),
                ('date_expire', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('Contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='gauge_checker.contact')),
                ('Measurements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='gauge_checker.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('Gauges', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='gauge_checker.gauge')),
                ('Group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='auth.group')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='gauge_checker.location')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('comments', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_name', to='gauge_checker.contact')),
                ('PropertyManagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_property_management', to='gauge_checker.contact')),
                ('Sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_site', to='gauge_checker.site')),
            ],
        ),
        migrations.CreateModel(
            name='Technican',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicans', to='gauge_checker.contact')),
            ],
        ),
    ]
