# Generated by Django 5.2.14 on 2026-05-09 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauge_checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gauge',
            name='Measurements',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='gauge_checker.measurement'),
        ),
    ]
