# Generated by Django 5.2.14 on 2026-05-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gauge_checker', '0002_alter_gauge_measurements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_name', to='gauge_checker.contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PropertyManagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_property_management', to='gauge_checker.contact'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Sites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers_by_site', to='gauge_checker.site'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='Contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gauges', to='gauge_checker.contact'),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='date_calibrated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='date_expire',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='date_installed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='last_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gauge',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gauge_checker.location'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/images/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='Images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='gauge_checker.images'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='date_measured',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='Gauges',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='gauge_checker.gauge'),
        ),
        migrations.AlterField(
            model_name='site',
            name='Group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='site',
            name='Location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='gauge_checker.location'),
        ),
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='technican',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technicans', to='gauge_checker.contact'),
        ),
    ]
