# Generated by Django 5.2.14 on 2026-05-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gauge_checker', '0003_alter_contact_address_alter_contact_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Kontakt', 'verbose_name_plural': 'Kontakte'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Kunde', 'verbose_name_plural': 'Kunden'},
        ),
        migrations.AlterModelOptions(
            name='gauge',
            options={'verbose_name': 'Messgerät', 'verbose_name_plural': 'Messgeräte'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Gruppe', 'verbose_name_plural': 'Gruppen'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Standort', 'verbose_name_plural': 'Standorte'},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'verbose_name': 'Messung', 'verbose_name_plural': 'Messungen'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Anlage', 'verbose_name_plural': 'Anlagen'},
        ),
        migrations.AlterModelOptions(
            name='technican',
            options={'verbose_name': 'Techniker', 'verbose_name_plural': 'Techniker'},
        ),
    ]
