# Generated by Django 5.2.14 on 2026-05-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gauge_checker', '0004_alter_contact_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
