# Generated by Django 5.2.14 on 2026-05-10 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gauge_checker', '0005_location_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Mitglied', 'verbose_name_plural': 'Mitglieder'},
        ),
        migrations.AlterModelOptions(
            name='gauge',
            options={'verbose_name': 'Wasserzähler', 'verbose_name_plural': 'Wasserzähler'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Gebiet', 'verbose_name_plural': 'Gebiete'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Installation', 'verbose_name_plural': 'Installationen'},
        ),
        migrations.AlterField(
            model_name='site',
            name='Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='auth.group'),
        ),
    ]
